// THE LONE WANDERER: 38 cartas para pegar en RONIN_NFTS (app.js). Generado desde 02_METADATA.
  {dir:'lone-wanderer',f:'lw-001',t:'The First Light',jt:'初光',r:'Rare',e:150,p:0.9,fx:'petals',bg:'pink-field',d:'Before the sun had a name, he was already awake.'},
  {dir:'lone-wanderer',f:'lw-002',t:'Silent Path',jt:'静かな道',r:'Common',e:200,p:0.5,fx:'leaves',bg:'cedar-path',d:'No one walks beside him.'},
  {dir:'lone-wanderer',f:'lw-003',t:'The Observer',jt:'観る者',r:'Common',e:200,p:0.5,fx:'leaves',bg:'meadow',d:'He cleans the scabbard before cleaning the blade, because what protects is tended first.'},
  {dir:'lone-wanderer',f:'lw-004',t:'Wandering Soul',jt:'彷徨う魂',r:'Common',e:200,p:0.5,fx:'seeds',bg:'meadow',d:'Seen from above, a man is only a line of intention crossing the water.'},
  {dir:'lone-wanderer',f:'lw-005',t:'The Beginning',jt:'始まり',r:'Common',e:200,p:0.5,fx:'clouds',bg:'above-clouds',d:'The mountain measured him before he took the first step, and found him sufficient.'},
  {dir:'lone-wanderer',f:'lw-006',t:'Sakura Dreams',jt:'桜の夢',r:'Epic',e:100,p:1.8,fx:'leaves',bg:'meadow',d:'The cherry tree spends everything it has in a single week and regrets nothing.'},
  {dir:'lone-wanderer',f:'lw-007',t:'The Green Valley',jt:'緑の谷',r:'Common',e:200,p:0.5,fx:'seeds',bg:'meadow',d:'The valley is older than every name anyone gave it.'},
  {dir:'lone-wanderer',f:'lw-008',t:'The Forest Guardian',jt:'森の守り人',r:'Common',e:200,p:0.5,fx:'leaves',bg:'cedar-path',d:'He looks up and the trees do not look back.'},
  {dir:'lone-wanderer',f:'lw-009',t:'Blooming Silence',jt:'咲く静寂',r:'Rare',e:150,p:0.9,fx:'petals',bg:'pink-field',d:'He lay down among the flowers to see whether the world continued without him.'},
  {dir:'lone-wanderer',f:'lw-010',t:'Mountain Spirit',jt:'山の霊',r:'Common',e:200,p:0.5,fx:'clouds',bg:'above-clouds',d:'From here the ranges look like waves that decided to stop.'},
  {dir:'lone-wanderer',f:'lw-011',t:'The Blade',jt:'刃',r:'Epic',e:100,p:1.8,fx:'dust',bg:'the-ground',d:'The blade is honest: it shows him his own face and asks what he intends to do with it.'},
  {dir:'lone-wanderer',f:'lw-012',t:'Meditation',jt:'瞑想',r:'Rare',e:150,p:0.9,fx:'bubbles',bg:'stillness',d:'Stillness is not absence of movement.'},
  {dir:'lone-wanderer',f:'lw-013',t:'The Ronin',jt:'浪人',r:'Common',e:200,p:0.5,fx:'dust',bg:'the-ground',d:'The salt plain keeps no footprints.'},
  {dir:'lone-wanderer',f:'lw-014',t:'Inner Strength',jt:'内なる力',r:'Rare',e:150,p:0.9,fx:'leaves',bg:'cedar-path',d:'The circle in the dust is not a ritual.'},
  {dir:'lone-wanderer',f:'lw-015',t:'The Oath',jt:'誓い',r:'Legendary',e:33,p:4.5,fx:'dust',bg:'the-ground',d:'He laid the blade down and knelt.'},
  {dir:'lone-wanderer',f:'lw-016',t:'The Storm',jt:'嵐',r:'Rare',e:150,p:0.9,fx:'clouds',bg:'above-clouds',d:'The storm does not single him out.'},
  {dir:'lone-wanderer',f:'lw-017',t:'Beyond Darkness',jt:'闇の彼方',r:'Common',e:200,p:0.5,fx:'clouds',bg:'above-clouds',d:'The mountain gives him no answer, and the silence turns out to be kinder than one.'},
  {dir:'lone-wanderer',f:'lw-018',t:'The Awakening',jt:'目覚め',r:'Epic',e:100,p:1.8,fx:'rays',bg:'stillness',d:'The light broke through and did not ask whether he deserved it.'},
  {dir:'lone-wanderer',f:'lw-019',t:'After the Rain',jt:'雨上がり',r:'Common',e:200,p:0.5,fx:'leaves',bg:'cedar-path',d:'The rain stopped and everything it touched kept shining.'},
  {dir:'lone-wanderer',f:'lw-020',t:'Rebirth',jt:'再生',r:'Common',e:200,p:0.5,fx:'petals',bg:'pink-field',d:'White flowers in a field that was ash.'},
  {dir:'lone-wanderer',f:'lw-021',t:'The Sacred Sun',jt:'聖なる日',r:'Epic',e:100,p:1.8,fx:'rays',bg:'dojo',d:'He does not pray to the sun.'},
  {dir:'lone-wanderer',f:'lw-022',t:'Eternal Peace',jt:'永遠の安らぎ',r:'Common',e:200,p:0.5,fx:'seeds',bg:'meadow',d:'A small man on a large hill, doing nothing of consequence.'},
  {dir:'lone-wanderer',f:'lw-023',t:'The Moon',jt:'月',r:'Rare',e:150,p:0.9,fx:'bubbles',bg:'stillness',d:'The moon has been cut in half for as long as anyone remembers, and has never complained about it.'},
  {dir:'lone-wanderer',f:'lw-024',t:'The Sacred Tree',jt:'御神木',r:'Rare',e:150,p:0.9,fx:'leaves',bg:'meadow',d:'The rope around the trunk marks what must not be cut.'},
  {dir:'lone-wanderer',f:'lw-025',t:'The Inner Temple',jt:'心の寺',r:'Rare',e:150,p:0.9,fx:'rays',bg:'dojo',d:'The temple has no roof, no door and no priest.'},
  {dir:'lone-wanderer',f:'lw-026',t:'The Last Journey',jt:'最後の旅',r:'Common',e:200,p:0.5,fx:'snow',bg:'sumi',d:'He walks toward the horizon knowing it will not arrive.'},
  {dir:'lone-wanderer',f:'lw-027',t:'The Eternal Ronin',jt:'永遠の浪人',r:'Rare',e:150,p:0.9,fx:'snow',bg:'sumi',d:'The snow settles on his shoulders as if he were part of the landscape.'},
  {dir:'lone-wanderer',f:'lw-028',t:'Beyond the Mountains',jt:'山の彼方',r:'Common',e:200,p:0.5,fx:'clouds',bg:'above-clouds',d:'Beyond the mountains there are more mountains.'},
  {dir:'lone-wanderer',f:'lw-029',t:'The Final Bloom',jt:'最後の花',r:'Common',e:200,p:0.5,fx:'petals',bg:'pink-field',d:'The last flowers open in the snow, out of season and out of sense.'},
  {dir:'lone-wanderer',f:'lw-030',t:'The Lone Wanderer',jt:'孤高の旅人',r:'Legendary',e:33,p:4.5,fx:'snow',bg:'sumi',d:'The last stars are leaving and the crescent moon, the same shape cut into his sword guard, dissolves into the first light.'},
  {dir:'lone-wanderer',f:'lw-031',t:'Dry Grass Vigil',jt:'枯れ野',r:'Rare',e:150,p:0.9,fx:'dust',bg:'the-ground',d:'Seen from above, kneeling in dead grass, he is a brushstroke someone left on a photograph of the world.'},
  {dir:'lone-wanderer',f:'lw-032',t:'Daylight Crescent',jt:'昼の三日月',r:'Epic',e:100,p:1.8,fx:'clouds',bg:'above-clouds',d:'A moon that forgot to leave when morning came.'},
  {dir:'lone-wanderer',f:'lw-033',t:'Golden Larch Path',jt:'落葉松の道',r:'Rare',e:150,p:0.9,fx:'leaves',bg:'cedar-path',d:'The larches turn gold and drop everything, every year, without ceremony.'},
  {dir:'lone-wanderer',f:'lw-034',t:'Blossom Palm',jt:'花の掌',r:'Rare',e:150,p:0.9,fx:'petals',bg:'pink-field',d:'He raises an open hand and a petal lands in it.'},
  {dir:'lone-wanderer',f:'lw-035',t:'Bamboo Rest',jt:'竹の休み',r:'Common',e:200,p:0.5,fx:'leaves',bg:'bamboo',d:'The bamboo creaks overhead like a house settling.'},
  {dir:'lone-wanderer',f:'lw-036',t:'Still Black Water',jt:'黒き静水',r:'Legendary',e:33,p:4.5,fx:'bubbles',bg:'stillness',d:'He let the black water hold him and stopped deciding.'},
  {dir:'lone-wanderer',f:'lw-037',t:'Pink Cosmos Cloud',jt:'秋桜の雲',r:'Common',e:200,p:0.5,fx:'petals',bg:'pink-field',d:'Pink to the horizon, clouds piled like something about to be said.'},
  {dir:'lone-wanderer',f:'lw-038',t:'Black Sand Tide',jt:'黒砂の潮',r:'Epic',e:100,p:1.8,fx:'bubbles',bg:'shore',d:'Black sand, white surf, and his sandals set neatly aside.'},
